name: CI

on:
  push:
    branches-ignore:
      - root

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Java task hasn't updated for the deprecation yet
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v1.0.0

        with:
          version: 1.15

      - name: Gradle (Build)
        run: sh gradlew build
