name: Publish

on:
  push:
    branches:
      - root

jobs:
  bot:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Java task hasn't updated for the deprecation yet
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v1.0.0

        with:
          version: 1.15

      - name: Gradle (Build)
        run: sh gradlew build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - run: docker build -t ghcr.io/fabricommunity/community-bot:latest -t ghcr.io/fabricommunity/community-bot:${GITHUB_SHA} .
      - run: docker push ghcr.io/fabricommunity/community-bot:latest
      - run: docker push ghcr.io/fabricommunity/community-bot:${GITHUB_SHA}
